project:
  type: website
  output-dir: docs
  resources:
    - /files
    - /img

website:
  title: "Alice Giampino"
  search: false
  navbar: 
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: other.qmd
        text: Other
      

format:
  html:
    page-layout: full
    theme: simplex
    css: styles.css
    toc: false
    fontsize: 1.3em

editor: visual