project:
  type: website
  output-dir: docs
  
# Meta
author-meta: "Alice Giampino"

website:
  title: "Alice Giampino"
  favicon: "img/icona.png"
  open-graph: true
  site-url: "https://AliceGiampino.github.io/"
  navbar:
    background: "#175e59"
    foreground: "light"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: other.qmd
        text: Other
      - text: CV
        href: files/CV_Alice_Giampino_May25.pdf
        target: _blank          
    right:
      - icon: envelope
        href: mailto:alice.giampino@unimib.it 
        target: _blank    
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=2x70sa0AAAAJ&hl=en&oi=ao
        target: _blank         
      - icon: github
        href: https://github.com/AliceGiampino
        target: _blank
    page-footer: 
      left: "[Alice Giampino](http://AliceGiampino.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    
    reader-mode: true



format:
  html:
    theme: [simplex, style.scss]
    favicon: "img/icona.png"  # or use icona.ico if you prefer
    toc: false
    link-external-newwindow: true
    email-obfuscation: javascript