---
title: "Research"
editor: 
  mode: source
---

I am interested on Bayesian Analysis, especially on Bayesian Nonparametric models. My research is based on exploring innovative approaches in model-based clustering. I am currently working on:

-   Bayesian clustering methods with high dimensional data;

-   Multivariate time series with change point detection.

-   Topic modelling techniques with distributions defined on the simplex.

## Research projects

-   **A. Giampino**, R. Ascari, S. Migliorati, *A flexible mixed-membership model for community and enterotype detection for microbiome data*.
Computational Statistics and Data Analysis (2025)
 [https://doi.org/10.1016/j.csda.2025.108181](https://doi.org/10.1016/j.csda.2025.108181).
-   **A. Giampino**, A. Canale, B. Nipoti, *A Bayesian Model for Co-clustering Ordinal Data with Informative Missing Entries*.
Statistics and Computing, (2025)
[https://doi.org/10.1007/s11222-025-10703-w](https://doi.org/10.1007/s11222-025-10703-w)
-   **A. Giampino**, B. Nipoti, M. Vannucci, M. Guindani, *Local Level Dynamic Random Partition Models for Changepoint Detection*. Accepted to Bayesian Analysis (2025) [https://arxiv.org/abs/2407.20085](arXiv:2407.20085)

## Books chapter & proceedings
- **A. Giampino**, R. Ascari, S. Migliorati.*Microbiome enterotype detection via a latent variable allocation model*, Methodological and Applied Statistics and Demography IV (SIS 2024), Springer (2025)
[https://doi.org/10.1007/978-3-031-64447-416](https://doi.org/10.1007/978-3-031-64447-416)
- **A. Giampino**, R. Ascari, S. Migliorati.*A Flexible Generalization of the Latent Dirichlet Allocation*, Data Analysis and Related
Applications 4: New Approaches, Volume 12 (ASMDA 2023), Wiley, (2024) [https://doi.org/10.1002/9781394316915.ch8](https://doi.org/10.1002/9781394316915.ch8)
- R. Ascari, **A. Giampino**,*A flexible topic model*, 14th Scientific Meeting of the Classification and Data Analysis Group (CLADAG
2023), Pearson, (2023)
[https://iris.unive.it/retrieve/a72dffc6-b72f-4356-9798-d1a2aad2baf5/CLADAG-2023-Bertarelli.pdf](https://iris.unive.it/.../CLADAG-2023-Bertarelli.pdf)

### Currently research projects
- A. Giampino, R. Ascari, S. Migliorati, *A flexible latent Dirichlet model for modelling taxa communities*, (2025+)
- A. Giampino, S. Migliorati, M. Guindani, *Temporal communities behaviour*, (2025+)
- A. Giampino, S. Migliorati, J. Vandekerckhove, M. Guindani, *A Bayesian Finite Mixture for Cognitive Data*, (2025+)
- J. Zonca, A. Giampino, C. Reverberi, P. Cherubini, *The advice gap: adaptive yet suboptimal advice integration* (2025+), PsyArXiv
[https://doi.org/10.31234/osf.io/4qkjev1](https://doi.org/10.31234/osf.io/4qkjev1)
Submitted to: Nature Communications


### Book of Abstract

- A. Giampino, R. Ascari, S. Migliorati,*A Flexible Latent Dirichlet Model for Modeling Taxa Communities*, ISBN
9788899594244, CLADAG (Sep 2025)
- A. Giampino, A. Canale & B. Nipoti, *Bayesian co-clustering of ordinal data with informative censoring*,  ISBN
978-9925-7812-8-7, CMStatistics (Dec 2024)
- A. Giampino, M. Guindani, B. Nipoti & M. Vannucci, *Changepoint detection with random partition models*, ISBN
978-9925-7812-7-0, CMStatistics (Dec 2023)
- R. Ascari & A. Giampino, *A Flexible Topic Model*,  ISBN 9788891935632, CLADAG (Sep 2023)
- R. Ascari & Giampino A. *A generalization of the latent Dirichlet allocation*, ISBN 978-9925-7812-6-3, CMStatistics
(Dec 2022)
- A. Giampino, R. Ascari & S. Migliorati *LEFDA: An extension of the classical LDA*, ISBN 978-90-73592-40-7,
COMPSTAT (Aug 2022)


## Awards

- BNP (Bayesin Nonparametrics) 2025:
Travel award

-   ISBA (International Society for Bayesian Analysis) 2024: Best poster

-   Ph.D. Fellowship, Nov 2019 - Oct 2023: University of Milano - Bicocca, Milan (Italy)

-   OBayes (Objective Bayes Methodology Conference) 2022: Travel award

-   ISBA (International Society for Bayesian Analysis) 2022: Travel award

-   SUS5 (Stats Under the Stars 5th edition) 2019: Winner of the statistical hackathon in 2019.
